SET-650 Update alignment report for EAP8 to compare channel rather than source code
jboss-set/cedalion pull request #117
Opened 2024-01-02 13:50 UTC by TomasHofman

https://issues.redhat.com/browse/SET-650

2024-01-02 15:29 UTC, spyrkob commented on pipelines/component-alignment-channel-pipeline
> +                    readonly SENDMAIL_URL='https://github.com/jboss-set/sendmail/releases/download/1.0.0/sendmail-1.0.0-jar-with-dependencies.jar'
Why do we need the sendmail program? Jenkins can send emails is that not enough?

2024-01-02 15:29 UTC, spyrkob commented on job-dsl-lib/alignment/channel/Builder.groovy
> +            jobName = 'component-alignment-' + jobSuffix
what is `jobSuffix`, I don't see it defined anywhere?

2024-01-02 15:32 UTC, spyrkob commented on pipelines/component-alignment-channel-pipeline
> +                    cat >channel.yaml <<EOF
I think the channel definition should be kept in gitlab or somewhere separate from the pipeline

2024-01-02 15:35 UTC, spyrkob requested changes
@TomasHofman IIUC this pipeline would be executed on the main Jenkins node. On Olympus the pipeline should start a container using hera and execute a harmonia script - @rpelisse correct me if I'm wrong

2024-01-02 15:59 UTC, TomasHofman commented on pipelines/component-alignment-channel-pipeline
> +                    readonly SENDMAIL_URL='https://github.com/jboss-set/sendmail/releases/download/1.0.0/sendmail-1.0.0-jar-with-dependencies.jar'
Do you mean the `emailext` extension?

2024-01-02 16:04 UTC, TomasHofman commented on pipelines/component-alignment-channel-pipeline
> +                    cat >channel.yaml <<EOF
Well I bit dislike having stuff spread around over unrelated repositories, when it's a single purpose file. What about having the file somewhere in this repo? But I would still rather keep it as it is.

2024-01-02 16:06 UTC, spyrkob commented on pipelines/component-alignment-channel-pipeline
> +                    readonly SENDMAIL_URL='https://github.com/jboss-set/sendmail/releases/download/1.0.0/sendmail-1.0.0-jar-with-dependencies.jar'
Yes

2024-01-02 16:08 UTC, spyrkob commented on pipelines/component-alignment-channel-pipeline
> +                    cat >channel.yaml <<EOF
Well, the channels can be reused and we have the https://gitlab.cee.redhat.com/jboss-set/channel-definitions for it. Having the definition here spreads it as well. Especially if this job were to be replicated in CCI

2024-01-02 16:10 UTC, TomasHofman commented
> @TomasHofman IIUC this pipeline would be executed on the main Jenkins node. On Olympus the pipeline should start a container using hera and execute a harmonia script - @rpelisse correct me if I'm wrong

I don't want to use hera & harmonia. What would be a benefit? That's again adding more repositories to otherwise trivial job. Also makes it impossible for operator to see what the job is doing. Is that necessary to have all this layers to run two bash commands?

Also, I don't like waiting 10 minutes for some node being provisioned by OpenStack or whatever it is. Does using the main Jenkins node cause some availability issues for the Jenkins instance? It is true this job can take some minutes.

2024-01-02 16:17 UTC, TomasHofman commented on job-dsl-lib/alignment/channel/Builder.groovy
> +            jobName = 'component-alignment-' + jobSuffix
I don't really know. I copied this from the `alignment.Builder` job, which was written by you :).

Looking at it closer, it is used by other builders where it's inherited from the `AbstractAnsibleBuilder`. This builder and `alignment.Builder` however do not inherit from the `AbstractAnsibleBuilder`, so it looks to be a relict that should be removed.

2024-01-02 16:25 UTC, spyrkob commented on job-dsl-lib/alignment/channel/Builder.groovy
> +            jobName = 'component-alignment-' + jobSuffix
hah I must have copied it too 😂  I think it can be removed from both. Actually probably the whole check can be removed and the jobName can be a required parameter

2024-01-02 16:30 UTC, spyrkob commented
> I don't want to use hera & harmonia. What would be a benefit? That's again adding more repositories to otherwise trivial job. Also makes it impossible for operator to see what the job is doing. Is that necessary to have all this layers to run two bash commands?

This is how Olympus works. Jenkins is running inside a docker container itself, I'm not sure what exact resources it has, but we should not be running anything on there.
 
> Also, I don't like waiting 10 minutes for some node being provisioned by OpenStack or whatever it is. Does using the main Jenkins node cause some availability issues for the Jenkins instance? It is true this job can take some minutes.

Olympus is not using Openstack, the docker containers are spun up locally it usually pretty quick

2024-01-05 11:06 UTC, TomasHofman commented on job-dsl-lib/alignment/channel/Builder.groovy
> +            jobName = 'component-alignment-' + jobSuffix
I removed the if statement.

2024-01-05 11:09 UTC, TomasHofman commented on pipelines/component-alignment-channel-pipeline
> +                    cat >channel.yaml <<EOF
The job would not be replicated, it would be relocated there if anything.

The channel definition in question is intended purely for the purpose of report generation, and is not to be reused by any other tooling at this point. It's not what we would reuse in EAP8 pipeline for instance.

2024-01-05 11:25 UTC, TomasHofman commented
> @TomasHofman IIUC this pipeline would be executed on the main Jenkins node.

![Screenshot from 2024-01-05 10-33-18](https://github.com/jboss-set/cedalion/assets/353221/87236572-d7e8-4b4e-8f38-bef6b333a7a3)

It appears to work as usual ^. There is 12 available runners, one of them was picked to run this job.

> On Olympus the pipeline should start a container using hera and execute a harmonia script.

I understand this in case of building EAP where we need isolation. I don't see any benefit here, it's just running a bash script.

Overall the script doesn't do anything that wouldn't be commonly done in our Jenkins jobs already, in terms of inlining bash scripts and injecting file contents, look here for instance: https://gitlab.cee.redhat.com/jboss-set/csb-jenkins-definition/-/blob/master/jobs/eap-8.0/pipeline-jobs/prospero-eap.groovy

Having these related bits versioned together makes maintenance far easier then when it's spread over three different repositories.

2024-01-05 13:21 UTC, spyrkob commented
The difference is other jobs only fire of a different container using the Jenkins executor and all other job is performed there. With this all of the work happens inside Jenkins container.

Either way, as @rpelisse knows Olympus better, I'll leave it to him.

2024-01-25 12:13 UTC, rpelisse commented
@TomasHofman I'm fine with jobs running directly on the master node (so the Jenkins Podman container), but you have to understand it's a constrained env (if you need a package install or a specific jdk, we WON'T add it to the container). Also, please, do break the server itself :)

2024-01-25 13:11 UTC, spyrkob commented on pipelines/component-alignment-channel-pipeline
> +                    readonly SENDMAIL_URL='https://github.com/jboss-set/sendmail/releases/download/1.0.0/sendmail-1.0.0-jar-with-dependencies.jar'
email-ext plugin has not been configured: https://github.com/jboss-set/zeus/pull/238

2024-02-09 08:27 UTC, rpelisse commented
@TomasHofman @spyrkob I'm try to clean up the queues of PR on Olympus related projects... Is this PR still under work? Can we close it/merge it?

2024-02-09 08:47 UTC, spyrkob commented
yes you can merge it

2024-02-09 08:50 UTC, merged

2024-02-09 15:23 UTC, TomasHofman commented
Thank you folks, the PR was as I preferred to keep it from my PoV :+1: